#
# Home
# 
export HOME=/Users/phynet

#
# JAVA Home (prints version in terminal)
#  

jhome () {
  export JAVA_HOME=`/usr/libexec/java_home $@`
  echo "JAVA_HOME:" $JAVA_HOME
  echo "java -version:"
  java -version
}

export JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home'

#
# Google Cloud SDK.
#  
export PATH=/Users/medianet/google-cloud-sdk/bin:$PATH
export PATH="$PATH:/Users/Myuser/Projects/AIRSDK_Compiler/bin/"
# The next line enables bash completion for gcloud.
source /Users/Myuser/google-cloud-sdk/arg_rc
# MacPorts Installer addition on 2014-01-16_at_13:59:03: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH


#
# terminal colors
#  
[[ -f ~/.bashrc ]] && . ~/.bashrc
export CLICOLOR=1
//export PS1="\[$(tput bold)\]\[$(tput setaf 3)\][\t \u >> \w:]\\$: \[$(tput sgr0)\]"


#
# git
# 
export PATH=/usr/local/git/bin:$PATH

#
# MySQL
# 
export PATH="/usr/local/mysql/bin:$PATH"


#
# Android
#  
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH_ANDROID=$PATH_ANDROID:$ANDROID_HOME:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/add-ons
export GRADLE_HOME=$HOME/gradle-2.2.1/bin
export PATH="$PATH_ANDROID/platform-tools:$GRADLE_HOME:$PATH"


#
# NPM
# 
export NPM_PATH=/usr/local/bin
export PATH="$PATH_ANDROID/platform-tools:$GRADLE_HOME:$NPM_PATH:$PATH"

#
# Node
#
export NODE_PATH=/usr/local/lib/node_modules/

#
# open files with sublime text, use: open whateeverfile
#
sudo ln -s /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl /usr/local/bin/sublime


#              #
#              #
#    ALIAS     #
#              #
#              #


#
# Reload Terminal with comand 
# 

alias reload="source ~/.bashrc"

#
# Jenkins 
# 

alias jstart="launchctl load ~/Library/LaunchAgents/homebrew.mxcl.jenkins.plist"
alias jstop="launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.jenkins.plist"

#
# Load RVM into a shell session *as a function*
#
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 

#          #
#   Utils  #
#          #

#
# Navigation
#
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

#
# Show/hide hidden files in Finder
#
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

#
# Reload Terminal with comand 
# 
alias reload="source ~/.bashrc"

#
#  Lock the screen (when going AFK) instead of the basic cmmd + shift + q this will present a 3D block screen
#
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

#
# XCODE 
#


# Cocoa Pods commands

alias pi="pod install"
alias bi="bundle install"
alias yolo="bi && pi"

# alias to change between xcodes

alias xcode73="sudo xcode-select --switch /Applications/xcode73/Xcode.app/Contents/Developer"
alias xcode731="sudo xcode-select --switch /Applications/xcode731/Xcode.app/Contents/Developer"
alias xcode8="sudo xcode-select --switch /Applications/xcode8/Xcode.app/Contents/Developer"

#
#  GIT Commands
#

#  Git alias, to remove .DS_Store files in project
alias git-ds="find . -name .DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch"

#  Git alias, to delete branch. Use: $ gitdb nameBranch
alias gitdb='function _branch_delete(){ echo "Deleting branch: $1"; git push origin --delete "$1"; };_branch_delete'

# Git Ammend
alias gammend="git commit --amend -m "

# Git Pull
alias gp = "git pull"

# Git Push
alias gpush = "git push"

# Git Status
alias gs='git status'

# Git Log
alias gl='git log'
